name: Build executable with PyInstaller (Linux)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: useblacksmith/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y upx  # Optional
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build Linux EXE
      run: |
        pyinstaller --onefile --noconsole --clean --noupx --name CSV-IServ-Converter --icon=icon.png --add-data "awthemes:awthemes" main.py

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-Linux
        path: dist/CSV-IServ-Converter
