name: Build executable with PyInstaller (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller customtkinter

    - name: Build Windows EXE (onedir)
      run: |
        pyinstaller CSV-IServ-Converter.spec

    - name: Upload Windows Artifact (onedir)
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-Windows
        path: dist/CSV-IServ-Converter/
