name: Build Executable (macOS)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build macOS EXE
      run: |
        pyinstaller --onefile --windowed --clean --name CSV-IServ-Converter main.py

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-macOS
        path: dist/CSV-IServ-Converter

