name: Build executable with PyInstaller (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build Windows EXE
      run: |
        pyinstaller --onefile --noconsole --clean --noupx --name CSV-IServ-Converter --icon=icon.ico --add-data "awthemes;awthemes" main.py


    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-Windows
        path: dist/CSV-IServ-Converter.exe
