name: Build executable with PyInstaller (Windows, macOS, Linux)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build Windows EXE
      run: |
        pyinstaller --onefile --noconsole --clean --noupx --name CSV-IServ-Converter --icon=icon.ico main.py

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-Windows
        path: dist/CSV-IServ-Converter.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build macOS EXE
      run: |
        pyinstaller --onefile --windowed --clean --name CSV-IServ-Converter main.py

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-macOS
        path: dist/CSV-IServ-Converter

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y upx  # Optional
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build Linux EXE
      run: |
        pyinstaller --onefile --clean --name CSV-IServ-Converter main.py

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-Linux
        path: dist/CSV-IServ-Converter
