name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller

    - name: Build with PyInstaller (onedir)
      run: |
        pyinstaller --onedir --noconsole --clean --noupx --name CSV-IServ-Converter --icon=icon.ico --add-data "awthemes;awthemes" main.py

    - name: Install Inno Setup
      run: |
        curl -L -o is.exe https://jrsoftware.org/download.php/is.exe
        Start-Process -Wait -FilePath is.exe -ArgumentList "/verysilent", "/dir=C:\InnoSetup"

    - name: Build Installer with Inno Setup
      run: |
        "C:\InnoSetup\ISCC.exe" installer.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: CSV-IServ-Converter-Installer
        path: Output/CSV-IServ-Converter-Setup.exe
